server:
  port: 8400

spring:
  application:
    name: user-services
    version: 1.0-SNAPSHOT
  mvc:
    throw-exception-if-no-handler-found: true
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 100
    leaseExpirationDurationInSeconds: 200
  healthcheck:
    enabled: true